# Site settings
title: Ana Carolina Coelho
description: Blog da Ana
keywords: Séries, playlist, pratos de comida
author: Ana
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
